# Generated by Django 5.0.6 on 2024-07-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional',
            name='user',
        ),
        migrations.AddField(
            model_name='professional',
            name='name',
            field=models.TextField(default='John Doe'),
        ),
        migrations.AddField(
            model_name='professional',
            name='prof_id',
            field=models.IntegerField(auto_created=True, default=0),
        ),
    ]
