# Generated by Django 4.2.13 on 2024-07-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional',
            name='user',
        ),
        migrations.AddField(
            model_name='professional',
            name='name',
            field=models.TextField(default='John Doe'),
        ),
    ]
